### ISSUE TITLE
How to calculate the coverage of the target program using afl instrumentation?

### ISSUE THREAD

**Issue by 1789120321** [s3team/Polyglot#2]
Hi @zr950624 , a lot of fuzzing is based on the coverage achieved by afl, but afl does not implement the coverage calculation method. I used afl-cov and clang to calculate the coverage, but the calculation efficiency would be seriously reduced due to too many seeds. How can I dynamically obtain the coverage of the target program?

**Comment by vanhauser-thc** [comment]
@1789120321 if you use afl++ the right value of "map density" in the UI will tell you the coverage achieved of all edges in percent

**Comment by 1789120321** [comment]
@vanhauser-thc, In Polyglot, the new edge found is used as the criterion for coverage comparison. I think the number of new edges can be calculated by a function called count_bytes in afl-fuzz. Is this calculation method correct?

**Comment by vanhauser-thc** [comment]
that calculation method is correct for a specific coverage of an input.
(if you use afl++ with a non-colliding instrumented target that is - if you use afl++ with CLASSIC instrumentation, afl-gcc or afl-gcc-fast - or any other afl variant - then you have colliding coverage and then you have no idea of the real coverage is)

**Comment by 1789120321** [comment]
@vanhauser-thc, you're right. After increasing the bitmap and reducing the probability of collisions, I think this method should be reasonable. There should be no problem with this understanding, right? Of course, before using AFL, I think the first task is to reduce collisions.

**Comment by vanhauser-thc** [comment]
I am not sure I understand your statement. what specific afl are you using? increasing the bitmap reduces the exec/s a lot, and you will always have the risk of collisions with collision coverage, increasing the map size just reduce the number and chances.

**Comment by 1789120321** [comment]
I am using the official afl. I understand what you mean. Using count_bytes to calculate the new edge is not accurate. I haven't read the source code of afl++ yet. Later, I will learn a afl++ code and learn how to accurately calculate the coverage.

**Comment by Changochen** [comment]
I agree with what you discussed. So `PolyGlot` is based on AFL so we only increase the bitmap size to reduce collision. 

> How can I dynamically obtain the coverage of the target program?

I guess you want to do it in real time. So AFL++'s colliding-free instrumentation might be the solution if you want the accurate coverage.

**Comment by 1789120321** [comment]
Yes it is. The paper PolyGlot and DIE both use graphs to compare the coverage, so I think it is necessary to operate the virgin_bits in afl in real time to obtain the coverage.
