### ISSUE TITLE
sql_grammar is missing in grammar folder

### ISSUE THREAD

**Issue by where2me** [s3team/Polyglot#6]
I try polyglot to fuzz SQLite. However, I find there is no sql_grammar in grammar folder.
I want to know how to use poly to do this, and how to write the semantic annotations for SQL language. Thanks.

**Comment by Changochen** [comment]
To use Polyglot to fuzz Sqlite, you can treat the table creation as variable defintion and the others as variable use (You can take a look at the c grammar as an example). This doesn't well capture the data dependency. A better way is to treat the table as the class, and its columns as member variables.

Or you can use https://github.com/s3team/Squirrel instead, which is specialized for database fuzzing.

**Comment by where2me** [comment]
Thanks for your reply, I'll try https://github.com/s3team/Squirrel.
