### ISSUE TITLE
Failed to instrument gcc.

### ISSUE THREAD

**Issue by alexs-repos** [s3team/Polyglot#8]
I encountered an issue while compiling gcc using afl-gcc/afl-g++. During the compilation process, it printed that instrumentation was being performed. However, when I tried running fuzzing, it aborts and saying that No instumentation detected.

test target: gcc-10.2.0
the configure parameters: configure --prefix=/gcc_build/gcc_binary --enable-checking=release --enable-languages=c,c++ --disable-multilib

while compiling, it shows that it has been instrumented:
![image](https://github.com/s3team/Polyglot/assets/69915263/f3017f44-a477-439f-ae05-ee5af2e479f5)

when I run fuzzing:
![image](https://github.com/s3team/Polyglot/assets/69915263/6d9a8ad4-95f1-4a75-8c6e-dffda7eed303)

Did I miss any settings or something else somewhere?

**Comment by Changochen** [comment]
We had this problem before. It is related to how GCC compilation works. If I remember correctly, building GCC will first compile a small working compiler, and then use that compiler to compile the rest of GCC. So you might need to figure out how to avoid that. (We chose to use the QEMU mode instead :) )

**Comment by Changochen** [comment]
If you prefer using AFLpp, you can take a look at our new version. (https://github.com/OMH4ck/PolyGlot)

**Comment by alexs-repos** [comment]
> We had this problem before. It is related to how GCC compilation works. If I remember correctly, building GCC will first compile a small working compiler, and then use that compiler to compile the rest of GCC. So you might need to figure out how to avoid that. (We chose to use the QEMU mode instead :) )

During the compilation configuration, I added the parameter **--disable-bootstrap** to solve this problem. Thank you for your reply.
