### ISSUE TITLE
Parser failed to parse 'BuiltinObjFile' directory files

### ISSUE THREAD

**Issue by Yeaseen** [s3team/Polyglot#9]
I came across the following issue when I tried to fuzz the gcc compiler. I compiled the gcc with afl-gcc and set the following directories properly. I just used python2 as python is no longer in Ubuntu. make on Polyglot worked fine.

<img width="861" alt="Screenshot 2023-09-03 at 12 16 30 AM" src="https://github.com/s3team/Polyglot/assets/19332990/a6e06ff4-51a2-43c0-b88c-78c73e8c989e">

But after running the fuzzing I found this error:

<img width="1165" alt="Screenshot 2023-09-03 at 12 24 18 AM" src="https://github.com/s3team/Polyglot/assets/19332990/179943c9-8a86-4121-9197-a4a119addea5">

Parsing failed here:: 

<img width="988" alt="Screenshot 2023-09-03 at 12 13 04 AM" src="https://github.com/s3team/Polyglot/assets/19332990/6099b7ba-409c-49cb-9a23-1701c7eefe35">

Hence, the following incorrect data: It says that the target application doesn't get the correct input (syntax error!) which is because the parser failed to parse the files under initial build in files directory. 

<img width="882" alt="Screenshot 2023-09-03 at 12 13 43 AM" src="https://github.com/s3team/Polyglot/assets/19332990/37d0155b-dcd8-4f46-a016-56264d6f3cd7">

After backtracing, I found the parser in typesystem.cpp failed to parse.

<img width="756" alt="Screenshot 2023-09-03 at 12 26 44 AM" src="https://github.com/s3team/Polyglot/assets/19332990/47d5a3b7-179f-418f-ba42-13f4afa383e4">

Did I miss something here? Thnak you!

**Comment by zr950624** [comment]
Hi Yeaseen,

Thanks for using our tool.
The `BuiltinObjFile` refers to the path of your builtin object definition. In your case, you use the grammar path for that, so it will fail to parse.

Please look at the example in `grammar/solidity_grammar/builtin` to know how to set up your builtin objects.

**Comment by Yeaseen** [comment]
Your reply is great. But it's all the same. Configured the path and added a block: 

<img width="782" alt="Screenshot 2023-09-03 at 2 43 27 AM" src="https://github.com/s3team/Polyglot/assets/19332990/3372ebc0-2c32-4dd3-9ed1-f03b5952ea11">

Now there's parsing failure. But afl is still saying syntax error: 

<img width="756" alt="Screenshot 2023-09-03 at 2 46 17 AM" src="https://github.com/s3team/Polyglot/assets/19332990/854477d9-4285-45ee-b518-a44ffe358dc0">

So in the seed inputs, I tried with both a main function and without any main function:
<img width="737" alt="Screenshot 2023-09-03 at 2 49 08 AM" src="https://github.com/s3team/Polyglot/assets/19332990/c1622706-7505-4f65-b9b5-987ea49a930a">

 

I am still uncertain whether my seed inputs are ok or not. It would be great for me if you provide me with a block sample and a test input for the gcc. Thank you again!!

**Comment by Yeaseen** [comment]
The error is in the AFL_Replace_Mutate/afl-fuzz.c file, where the currently mutated file is being saved with a Java extension(search for ./cur_input.java) not desired for any target application that doesn't accept a Java file. You can still use AFL's "-f" option that accepts a modified target name.
